controller_list:
  - name: trajectory_controller
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints: 
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: gripper_controller
    action_ns: gripper_cmd
    type: GripperCommand
    command_joint: robotiq_85_left_knuckle_joint
    joints: 
      - robotiq_85_left_knuckle_joint